### ISSUE TITLE
pending, "ReqNodeNotAvail, Reserved for maintenance."

### ISSUE THREAD

**Issue by nclowell** [merlab-uw/Klone#2]
Hi @EleniLPetrou and @ctarpey!

I submitted a couple of nearly identical jobs last week, hoping one would run right after the other. The first ran perfectly fine and finished a few days ago, the second said pending, "ReqNodeNotAvail, Reserved for maintenance." Any idea what that's about?

![Screen Shot 2021-06-06 at 10 41 03 AM](https://user-images.githubusercontent.com/22554275/120934900-2362f480-c6b5-11eb-944f-f7712cad3b81.png)

**Comment by nclowell** [comment]
Oh it gets weirder! So first it was pending, "ReqNodeNotAvail", then it was running

![Screen Shot 2021-06-06 at 10 57 11 AM](https://user-images.githubusercontent.com/22554275/120935144-34603580-c6b6-11eb-94db-f3662104dfc3.png)

And then I checked it again and it's pending again?

![Screen Shot 2021-06-06 at 10 57 30 AM](https://user-images.githubusercontent.com/22554275/120935147-388c5300-c6b6-11eb-9781-f13df3ff4464.png)

**Comment by EleniLPetrou** [comment]
The administrators generally do maintenance on Klone on Tuesdays (this practice was suspended for a couple of weeks in May), so your job might be getting blocked from running if it is going to take multiple days and have to run over a Tuesday. I would shoot Nam or UW IT an email and check with them.

**Comment by nclowell** [comment]
Thanks @EleniLPetrou! I think that's it. Looks like maintenance is the second Tues of the month, and the wall time for the jobs that are pending all went through Tuesday. Mystery solved!
